name: deploy-snapshot

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - run: echo "VERSION=1.0-$(echo ${{ github.ref_name }} | tr / -)-$(echo ${{ github.sha }} | cut -c 1-6)-SNAPSHOT" >> "$GITHUB_ENV"

      - run: ./gradlew --no-daemon publish -Pversion=$VERSION -Pgpr.user=${{ github.actor }} -Pgpr.key=${{ secrets.GITHUB_TOKEN }}
